import { assertDefined } from "../assert-defined";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import {
  applySystemUpdate,
  getLocalSystemUpdateStatus,
  getSystemUpdateStatus,
  parseChecksum,
  readCurrentVersion,
  RUNTIME_UPDATE_ENTRIES,
} from "@/lib/system/release-update";
import { ownership } from "@/lib/runtime/ownership-state";

describe("release artifact updater", () => {
  it("parses sha256 checksum files generated by the release workflow", () => {
    expect(
      parseChecksum(
        `${"f".repeat(64)}  toolplane-runtime-linux-amd64.tar.gz\n`,
        "toolplane-runtime-linux-amd64.tar.gz",
      ),
    ).toBe("f".repeat(64));
    expect(
      parseChecksum("bad checksum\n", "toolplane-runtime-linux-amd64.tar.gz"),
    ).toBeNull();
  });

  it("falls back to TOOLPLANE_VERSION when old images do not have a version file", async () => {
    const previous = process.env.TOOLPLANE_VERSION;
    process.env.TOOLPLANE_VERSION = "sha-test";
    await expect(
      readCurrentVersion("/definitely/missing/toolplane"),
    ).resolves.toBe("sha-test");
    if (previous === undefined) delete process.env.TOOLPLANE_VERSION;
    else process.env.TOOLPLANE_VERSION = previous;
  });

  it("uses package metadata as the development version", async () => {
    const root = await mkdtemp(path.join(tmpdir(), "toolplane-version-"));
    const previous = process.env.TOOLPLANE_VERSION;
    try {
      delete process.env.TOOLPLANE_VERSION;
      await writeFile(
        path.join(root, "package.json"),
        JSON.stringify({ version: "0.22.0" }),
      );
      await expect(readCurrentVersion(root)).resolves.toBe("0.22.0");
    } finally {
      if (previous === undefined) delete process.env.TOOLPLANE_VERSION;
      else process.env.TOOLPLANE_VERSION = previous;
      await rm(root, { recursive: true, force: true });
    }
  });

  it("returns local version status without requiring a configured runtime root", async () => {
    const previous = process.env.TOOLPLANE_VERSION;
    try {
      process.env.TOOLPLANE_VERSION = "v-local";
      await expect(getLocalSystemUpdateStatus()).resolves.toMatchObject({
        runtimeId: expect.any(String),
        currentVersion: "v-local",
        artifactName: "toolplane-runtime-linux-amd64.tar.gz",
        updateJob: {
          status: "idle",
          targetVersion: null,
        },
      });
    } finally {
      if (previous === undefined) delete process.env.TOOLPLANE_VERSION;
      else process.env.TOOLPLANE_VERSION = previous;
    }
  });

  it("reports update readiness only after ownership recovery finishes", async () => {
    const previousStatus = ownership.status;
    const previousFixture = process.env.TOOLPLANE_TEST_RUNTIME_OWNER;
    process.env.TOOLPLANE_TEST_RUNTIME_OWNER = "1";
    try {
      ownership.status = "blocked";
      expect((await getLocalSystemUpdateStatus()).runtimeReady).toBe(false);
      ownership.status = "recovering";
      expect((await getLocalSystemUpdateStatus()).runtimeReady).toBe(false);
      ownership.ready();
      expect((await getLocalSystemUpdateStatus()).runtimeReady).toBe(true);
      ownership.status = "draining";
      expect((await getLocalSystemUpdateStatus()).runtimeReady).toBe(false);
    } finally {
      ownership.status = previousStatus;
      if (previousFixture === undefined)
        delete process.env.TOOLPLANE_TEST_RUNTIME_OWNER;
      else process.env.TOOLPLANE_TEST_RUNTIME_OWNER = previousFixture;
    }
  });

  it("does not update an unconfigured runtime root", async () => {
    const previousEnabled = process.env.TOOLPLANE_UPDATE_ENABLED;
    const previousRoot = process.env.TOOLPLANE_RUNTIME_ROOT;
    try {
      process.env.TOOLPLANE_UPDATE_ENABLED = "true";
      delete process.env.TOOLPLANE_RUNTIME_ROOT;

      await expect(getSystemUpdateStatus()).resolves.toMatchObject({
        enabled: true,
        canUpdate: false,
        reason: "Runtime directory is not configured.",
      });
    } finally {
      if (previousEnabled === undefined)
        delete process.env.TOOLPLANE_UPDATE_ENABLED;
      else process.env.TOOLPLANE_UPDATE_ENABLED = previousEnabled;
      if (previousRoot === undefined) delete process.env.TOOLPLANE_RUNTIME_ROOT;
      else process.env.TOOLPLANE_RUNTIME_ROOT = previousRoot;
    }
  });
});

describe("release installation shutdown boundary", () => {
  const globals = globalThis as typeof globalThis & {
    __toolplaneShutdown?: () => Promise<boolean>;
    __toolplaneSystemUpdateJob?: unknown;
  };
  let root: string | undefined;
  const originalShutdown = globals.__toolplaneShutdown;
  const signalHandler = () => undefined;

  afterEach(async () => {
    process.removeListener("SIGTERM", signalHandler);
    globals.__toolplaneShutdown = originalShutdown;
    delete globals.__toolplaneSystemUpdateJob;
    vi.restoreAllMocks();
    vi.unstubAllGlobals();
    vi.unstubAllEnvs();
    if (root) await rm(root, { recursive: true, force: true });
  });

  async function prepareRelease() {
    root = await mkdtemp(path.join(tmpdir(), "toolplane-update-shutdown-"));
    const payload = path.join(root, "payload");
    await mkdir(path.join(payload, "app"), { recursive: true });
    for (const entry of RUNTIME_UPDATE_ENTRIES) {
      await writeFile(path.join(payload, "app", entry), "new-release");
      await writeFile(path.join(root, entry), "old-release");
    }
    const artifact = "toolplane-runtime-linux-amd64.tar.gz";
    const archive = path.join(root, artifact);
    await promisify(execFile)("tar", ["-czf", archive, "-C", payload, "app"]);
    const bytes = new Uint8Array(await readFile(archive));
    const checksum = createHash("sha256").update(bytes).digest("hex");
    const base = "https://github.com/asharca/ToolPlane/releases/download/test/";
    vi.stubEnv("TOOLPLANE_RUNTIME_ROOT", root);
    vi.stubEnv("TOOLPLANE_UPDATE_ENABLED", "true");
    vi.stubEnv("TOOLPLANE_UPDATE_ARTIFACT", artifact);
    vi.stubEnv("TOOLPLANE_RESTART_DELAY_MS", "250");
    vi.stubEnv("TOOLPLANE_GITHUB_TOKEN", "");
    vi.stubEnv("GITHUB_TOKEN", "");
    vi.stubGlobal("fetch", async (url: string) => {
      if (url.startsWith("https://api.github.com/")) {
        return Response.json({
          tag_name: "new-release",
          assets: [
            { name: artifact, browser_download_url: base + artifact },
            {
              name: `${artifact}.sha256`,
              browser_download_url: `${base}${artifact}.sha256`,
            },
          ],
        });
      }
      const response = new Response(
        url.endsWith(".sha256") ? `${checksum}  ${artifact}` : bytes,
      );
      Object.defineProperty(response, "url", { value: url });
      return response;
    });
    process.on("SIGTERM", signalHandler);
    return vi.spyOn(process, "kill").mockReturnValue(true);
  }

  it("keeps the old release until shutdown completes, then requests managed restart", async () => {
    const kill = await prepareRelease();
    let finishShutdown!: (clean: boolean) => void;
    const drained = new Promise<boolean>((resolve) => {
      finishShutdown = resolve;
    });
    globals.__toolplaneShutdown = vi.fn(() => drained);
    await expect(applySystemUpdate()).resolves.toMatchObject({
      ok: true,
      status: "updating",
    });
    await vi.waitFor(() =>
      expect(globals.__toolplaneShutdown).toHaveBeenCalledOnce(),
    );
    expect(
      await readFile(
        path.join(assertDefined(root), ".toolplane-version"),
        "utf8",
      ),
    ).toBe("old-release");
    expect(kill).not.toHaveBeenCalled();
    finishShutdown(true);
    await vi.waitFor(() =>
      expect(kill).toHaveBeenCalledWith(process.pid, "SIGTERM"),
    );
    expect(
      await readFile(
        path.join(assertDefined(root), ".toolplane-version"),
        "utf8",
      ),
    ).toBe("new-release");
  });

  it.each(["unclean", "missing"] as const)(
    "preserves the old release and refuses restart when shutdown is %s",
    async (state) => {
      const kill = await prepareRelease();
      globals.__toolplaneShutdown =
        state === "unclean" ? async () => false : undefined;
      await applySystemUpdate();
      await vi.waitFor(async () => {
        expect((await getLocalSystemUpdateStatus()).updateJob.status).toBe(
          "failed",
        );
      });
      expect(
        await readFile(
          path.join(assertDefined(root), ".toolplane-version"),
          "utf8",
        ),
      ).toBe("old-release");
      expect(kill).not.toHaveBeenCalled();
    },
  );
});
