import { describe, expect, it } from 'vitest';
import {
  getSystemUpdateStatus,
  parseChecksum,
  readCurrentVersion,
  RUNTIME_UPDATE_ENTRIES,
} from '@/lib/system/release-update';

describe('release artifact updater', () => {
  it('parses sha256 checksum files generated by the release workflow', () => {
    expect(
      parseChecksum(
        'f'.repeat(64) + '  toolplane-runtime-linux-amd64.tar.gz\n',
        'toolplane-runtime-linux-amd64.tar.gz',
      ),
    ).toBe('f'.repeat(64));
    expect(parseChecksum('bad checksum\n', 'toolplane-runtime-linux-amd64.tar.gz')).toBeNull();
  });

  it('updates the runtime entries that are needed by docker-entrypoint', () => {
    expect(RUNTIME_UPDATE_ENTRIES).toEqual([
      '.next',
      'node_modules',
      'public',
      'package.json',
      'next.config.ts',
      'scripts',
      'prisma',
      'prisma.config.ts',
      '.toolplane-version',
    ]);
  });

  it('falls back to TOOLPLANE_VERSION when old images do not have a version file', async () => {
    const previous = process.env.TOOLPLANE_VERSION;
    process.env.TOOLPLANE_VERSION = 'sha-test';
    await expect(readCurrentVersion('/definitely/missing/toolplane')).resolves.toBe('sha-test');
    if (previous === undefined) delete process.env.TOOLPLANE_VERSION;
    else process.env.TOOLPLANE_VERSION = previous;
  });

  it('does not update an unconfigured runtime root', async () => {
    const previousEnabled = process.env.TOOLPLANE_UPDATE_ENABLED;
    const previousRoot = process.env.TOOLPLANE_RUNTIME_ROOT;
    try {
      process.env.TOOLPLANE_UPDATE_ENABLED = 'true';
      delete process.env.TOOLPLANE_RUNTIME_ROOT;

      await expect(getSystemUpdateStatus()).resolves.toMatchObject({
        enabled: true,
        canUpdate: false,
        reason: 'Runtime directory is not configured.',
      });
    } finally {
      if (previousEnabled === undefined) delete process.env.TOOLPLANE_UPDATE_ENABLED;
      else process.env.TOOLPLANE_UPDATE_ENABLED = previousEnabled;
      if (previousRoot === undefined) delete process.env.TOOLPLANE_RUNTIME_ROOT;
      else process.env.TOOLPLANE_RUNTIME_ROOT = previousRoot;
    }
  });
});
